title: "ًWelcome"
description: "Software development student at Tuwaiq Bootcamp – learning in public."
theme: jekyll-theme-cayman

url: "https://nawafalzanbaqi.github.io"
author: "Nawaf Alzanbaqi"

linkedin_url: "https://www.linkedin.com/in/nawaf-alzanbaqi"
github_username: "Nawafalzanbaqi"
email: "alzanbaqinawaf@gmail.com"

plugins:
  - jekyll-seo-tag
